<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <UserSecretsId>778470e3-eb27-423f-beed-e946fb7def9d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
	<PackageReference Include="Microsoft.OpenApi" Version="2.9.0" />
	<PackageReference Include="Scalar.AspNetCore" Version="2.14.11" />
	<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
	<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.16.0" />
	<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.16.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.16.0-beta.1" />
	<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.16.0" />
	<PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0-develop.154" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyJwtAuthServer.Contracts\MyJwtAuthServer.Contracts.csproj" />
  </ItemGroup>

</Project>
